CONTIKI_PROJECT = tftp-monitor
MAKEFLAGS += -j
all: $(CONTIKI_PROJECT)

PROJECT_SOURCEFILES += zoul_dualmote2.c zoul_dualmote2_io.c

CONTIKI = ../..

MAKE_ROUTING = MAKE_ROUTING_RPL_CLASSIC

include $(CONTIKI)/Makefile.include